# Generated by Django 3.2.8 on 2022-01-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientModel',
            fields=[
                ('idPatient', models.IntegerField(db_column='ИдПациент', primary_key=True, serialize=False, unique=True)),
                ('LastName', models.CharField(blank=True, db_column='Фамилия', max_length=50, null=True)),
                ('FirstName', models.CharField(blank=True, db_column='Имя', max_length=15, null=True)),
                ('MiddleName', models.CharField(blank=True, db_column='Отчество', max_length=30, null=True)),
                ('CardNumber', models.CharField(blank=True, db_column='НомКарты', max_length=10, null=True)),
                ('ReceiptDate', models.DateTimeField(blank=True, db_column='ДатаПоступления', null=True)),
                ('Department', models.CharField(blank=True, choices=[['приемное', 'приемное'], ['отказные', 'отказные'], ['терапевтическое', 'терапевтическое'], ['ифекционное', 'ифекционное'], ['для больных с ОНМК', 'для больных с ОНМК']], db_column='Отделение', default='приемное', max_length=255, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PatientRecordsModel',
            fields=[
                ('IdRecord', models.IntegerField(db_column='IdRecord', primary_key=True, serialize=False, unique=True)),
                ('idPatient', models.IntegerField(db_column='IdPatient', unique=True)),
                ('TypeRecord', models.CharField(blank=True, db_column='TypeRecord', max_length=50, null=True)),
                ('Department', models.CharField(blank=True, db_column='Department', max_length=50, null=True)),
                ('ContentRec', models.TextField(blank=True, db_column='ContentRec', null=True)),
                ('DateTime', models.DateTimeField(blank=True, db_column='DateTime', null=True)),
            ],
            options={
                'db_table': 'patientrecords',
            },
        ),
    ]
